$(document).ready(function(){
  $('.owl-carousel').owlCarousel({
    loop:true,
    margin:30,
    nav:true,
    dots:false,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            dots:true
        },
        600:{
            items:2,
            dots:true
        },
        1000:{
            items:3,
            dots:true,
            loop:true
        },
        1920: {
        	items:3,
        	nav:true,
        	loop:true
        }
    }
})
});